# Generated by Django 2.0.8 on 2018-10-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_name', models.CharField(choices=[('l', 'lung'), ('b', 'breast')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Snp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snp', models.CharField(max_length=50)),
                ('rareall', models.CharField(max_length=2)),
                ('value', models.IntegerField(default=1)),
                ('coeff', models.IntegerField(default=1)),
                ('link', models.CharField(max_length=100)),
                ('cancertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Cancer')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Gene')),
            ],
        ),
    ]
